from Task import Task
from time import sleep

# student = Task(241438010104, 123456)
# student = Task(231416100122, 123456)
# student = Task(241537011123, 123456)

with Task(231416100122, 123456) as student:

    print("进入实验主页")
    print("准备进入!项目二任务一")
    student_task = student.choose_project_task(2, 1)
    headers = student.get_headers_token(student_task)
    student.do_question_2112(headers)
    student_task.reload()
    student_task_2 = student.start_practice(student_task, 2, 2)
    print("准备提交!项目二任务一")
    student.submit_and_confirm(student_task, (1220, 80), (1220, 170))
    print("提交完成!!!")
    print("完成!项目二任务一")
    student.close_current_and_return()

    print("准备进入实验主页")
    print("准备进入!项目二任务二")
    student_task = student.choose_project_task(2, 2)
    sleep(10)
    student_task_2 = student.start_practice(student_task, 2, 2)
    sleep(10)
    print("获取cookie")
    cookie = student.get_headers_cookie(page=student_task_2, url_keyword="https://bi.suitanglian.com:3012/api/bitools/apiSaveProcessNodes")
    print(cookie)
    student.do_question_2222(cookie)
    student_task.reload()
    sleep(10)
    student_task_2 = student.start_practice(student_task, 2, 2)
    print("准备提交!项目二任务二")
    student.submit_and_confirm(student_task, (1220, 80), (1220, 170))
    print("提交完成!!!")
    print("完成!项目二任务二")
    student.close_current_and_return()



    print("准备进入!项目三任务一")
    student_task = student.choose_project_task(3, 1)
    headers = student.get_headers_token(student_task)
    student.do_question_3112()
    student.do_question_3122(headers)
    student_task.reload()
    student.start_practice(student_task, 2, 2)
    print("准备提交!项目三任务一")
    student.submit_and_confirm(student_task, (860, 80), (890, 180))
    print("提交完成!!!")
    print("完成!项目三任务一")
    student.close_current_and_return()
